name: styrketrening
description: "Karo's styrketrening â€“ enkel og tydelig treningslogg i Karo-universet."
publish_to: 'none'

version: 1.0.2+5

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  share_plus: ^10.0.2
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/splash/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/splash/splash.png
  fullscreen: true
  android: true
  ios: true
  android_12:
    image: assets/splash/splash.png

