name: styrketrening
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  path_provider: ^2.1.4

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

  # Nye for backup/export/import:
  share_plus: ^10.0.2
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # disse to trenger du ikke her, de ligger allerede over i dependencies
  # shared_preferences: ^2.2.2
  # path_provider: ^2.1.4

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # legg til ikon-mappen her hvis du ikke allerede har gjort det:
  assets:
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

